import { C, SF, SFText, SFMono } from './theme';

// Shared style object. Function entries are helpers that need state-derived values.
export const s = {
  nav: (scrolled) => ({
    position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
    padding: '0 48px', height: 64,
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    transition: 'background 0.4s, border-color 0.4s',
    background: scrolled ? 'rgba(10,13,12,0.85)' : 'transparent',
    backdropFilter: scrolled ? 'blur(22px)' : 'none',
    WebkitBackdropFilter: scrolled ? 'blur(22px)' : 'none',
    borderBottom: `1px solid ${scrolled ? C.border : 'transparent'}`,
  }),
  navLogo: { display: 'flex', alignItems: 'center', textDecoration: 'none' },
  logoText: { fontFamily: SF, fontSize: 11, fontWeight: 600, letterSpacing: '0.14em', textTransform: 'uppercase', color: C.text, lineHeight: 1.2, opacity: 0.9 },
  navLinks: { display: 'flex', gap: 36, listStyle: 'none', margin: 0, padding: 0, position: 'absolute', left: '50%', transform: 'translateX(-50%)' },
  navLink: { fontSize: 13.5, color: C.muted, textDecoration: 'none', fontWeight: 400, fontFamily: SFText },
  navCta: { fontSize: 13.5, color: C.gold, textDecoration: 'none', fontWeight: 500, fontFamily: SFText, borderBottom: '1px solid rgba(211,185,136,0.4)', paddingBottom: 1 },

  hero: { position: 'relative', height: '100vh', minHeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', background: C.bg },
  blindsWrap: { position: 'absolute', top: '-25%', left: 0, right: 0, width: '100%', height: '150%', zIndex: 0, pointerEvents: 'none' },
  vignette: { position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 80% 70% at 50% 50%, transparent 30%, #0A0D0C 100%)', zIndex: 1, pointerEvents: 'none' },
  vignetteBottom: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 200, background: 'linear-gradient(to bottom, transparent, #0A0D0C)', zIndex: 2, pointerEvents: 'none' },
  heroContent: { position: 'relative', zIndex: 10, textAlign: 'center', padding: '0 24px', maxWidth: 1160 },
  badge: { display: 'inline-flex', alignItems: 'center', gap: 8, padding: '7px 16px', border: '1px solid rgba(211,185,136,0.25)', borderRadius: 9999, background: 'rgba(211,185,136,0.05)', fontSize: 12, fontWeight: 500, color: C.gold, letterSpacing: '0.04em', marginBottom: 32, fontFamily: SFText },
  badgeDot: { width: 5, height: 5, borderRadius: '50%', background: C.gold },
  h1: { fontFamily: SF, fontSize: 'clamp(36px,5.8vw,72px)', fontWeight: 700, lineHeight: 0.98, letterSpacing: '-0.025em', color: C.text, marginBottom: 24, maxWidth: 1080, marginInline: 'auto' },
  heroSub: { fontSize: 'clamp(15px,1.5vw,18px)', color: C.muted, lineHeight: 1.65, maxWidth: 700, margin: '0 auto 40px', fontFamily: SFText },
  heroBtns: { display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' },
  btnPrimary: { padding: '14px 32px', background: C.text, color: C.bg, border: 'none', borderRadius: 9999, fontFamily: SFText, fontSize: 14, fontWeight: 500, transition: 'background 0.25s, transform 0.15s', textDecoration: 'none', display: 'inline-block' },
  btnGhost: { padding: '14px 32px', background: 'rgba(255,255,255,0.07)', color: C.text, border: '1px solid rgba(255,255,255,0.1)', borderRadius: 9999, fontFamily: SFText, fontSize: 14, fontWeight: 400, transition: 'all 0.25s', textDecoration: 'none', display: 'inline-block' },

  scrollInd: { position: 'absolute', bottom: 36, left: '50%', transform: 'translateX(-50%)', zIndex: 10, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 },
  scrollLabel: { fontSize: 10, fontFamily: SFMono, letterSpacing: '0.18em', color: C.muted, textTransform: 'uppercase' },
  scrollLine: { width: 1, height: 40, background: `linear-gradient(to bottom, ${C.muted}, transparent)` },

  statsBar: { borderTop: `1px solid ${C.border}`, borderBottom: `1px solid ${C.border}`, background: 'rgba(15,20,16,0.62)', padding: '0 48px' },
  statsInner: { maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(4,1fr)' },
  statItem: (i) => ({ padding: '20px 18px', textAlign: 'center', borderRight: i < 3 ? `1px solid ${C.border}` : 'none' }),
  statVal: { fontFamily: SF, fontSize: 24, fontWeight: 600, color: 'rgba(240,237,230,0.9)', lineHeight: 1, marginBottom: 4, letterSpacing: '-0.01em' },
  statLabel: { fontSize: 10.5, color: 'rgba(122,148,144,0.82)', letterSpacing: '0.14em', textTransform: 'uppercase', fontFamily: SFMono },

  introSection: { padding: '122px 48px 44px', background: C.bg },
  introShell: {
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    padding: '42px 36px',
    background: 'linear-gradient(180deg, rgba(15,20,16,0.58), rgba(10,13,12,0.78))',
  },
  introGrid: { display: 'grid', gridTemplateColumns: '1fr', gap: 28, alignItems: 'stretch' },
  introTextWrap: { paddingRight: 8 },
  introVisual: {
    position: 'relative',
    minHeight: 380,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    overflow: 'hidden',
    background: 'linear-gradient(145deg, rgba(22,37,35,0.95) 0%, rgba(15,20,16,0.96) 55%, rgba(19,26,20,0.98) 100%)',
  },
  introVisualGlow: {
    position: 'absolute',
    width: 260,
    height: 260,
    right: -60,
    top: -40,
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(211,185,136,0.22) 0%, rgba(211,185,136,0) 70%)',
    pointerEvents: 'none',
  },
  introVisualOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'radial-gradient(circle at 20% 20%, rgba(92,127,120,0.2), transparent 40%), linear-gradient(180deg, transparent 0%, rgba(10,13,12,0.45) 100%)',
    pointerEvents: 'none',
  },
  introVisualContent: {
    position: 'relative',
    zIndex: 2,
    height: '100%',
    padding: 24,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  introVisualLabel: { fontFamily: SFMono, fontSize: 10, letterSpacing: '0.16em', textTransform: 'uppercase', color: C.gold },
  introVisualTitle: { fontFamily: SF, fontSize: 26, lineHeight: 1.15, color: C.text, letterSpacing: '-0.01em', maxWidth: 280 },
  introVisualMeta: { fontSize: 13, color: C.muted, fontFamily: SFText, lineHeight: 1.6, maxWidth: 300 },
  introBars: { display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 8, alignItems: 'end', marginTop: 18 },
  introBar: (h, i) => ({
    height: h,
    borderRadius: 4,
    background: i % 2 ? 'linear-gradient(to top, rgba(92,127,120,0.9), rgba(37,64,58,0.6))' : 'linear-gradient(to top, rgba(211,185,136,0.9), rgba(112,95,69,0.55))',
    border: `1px solid ${C.border}`,
  }),

  servicesSection: { padding: '74px 48px 144px', background: C.bg },
  servicesHeadWrap: {
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    padding: '34px 32px',
    background: 'linear-gradient(180deg, rgba(10,13,12,0.75), rgba(19,26,20,0.62))',
    marginBottom: 58,
  },
  servicesBodyWrap: {
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    padding: '0',
    overflow: 'hidden',
    background: 'linear-gradient(180deg, rgba(10,13,12,0.52), rgba(15,20,16,0.64))',
  },
  servicesHeadGrid: { display: 'grid', gridTemplateColumns: '1.1fr 0.9fr', gap: 28, alignItems: 'end' },
  servicesLead: { fontSize: 16, color: C.muted, lineHeight: 1.7, maxWidth: 520, fontFamily: SFText },

  section: (bg = C.bg) => ({ padding: '120px 48px', background: bg }),
  inner: { maxWidth: 1200, margin: '0 auto' },
  eyebrow: { fontFamily: SFMono, fontSize: 11, letterSpacing: '0.2em', textTransform: 'uppercase', color: C.green, marginBottom: 18, display: 'flex', alignItems: 'center', gap: 12 },
  h2: { fontFamily: SF, fontSize: 'clamp(32px,4vw,52px)', fontWeight: 600, lineHeight: 1.08, letterSpacing: '-0.02em', color: C.text, marginBottom: 20 },
  subText: { fontSize: 16, color: C.muted, lineHeight: 1.65, maxWidth: 480, fontFamily: SFText },

  servicesGrid: { display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 1, background: C.border, borderTop: `1px solid ${C.border}`, marginTop: 64 },
  card: (hovered) => ({ background: hovered ? C.surface2 : C.surface, padding: '40px 36px', position: 'relative', overflow: 'hidden', transition: 'background 0.25s' }),
  cardTopBorder: (hovered) => ({ position: 'absolute', top: 0, left: 0, right: 0, height: 2, background: C.green, transform: hovered ? 'scaleX(1)' : 'scaleX(0)', transformOrigin: 'left', transition: 'transform 0.35s ease' }),
  cardNum: { position: 'absolute', top: 24, right: 28, fontFamily: SFMono, fontSize: 11, color: 'rgba(122,148,144,0.4)', letterSpacing: '0.08em' },
  cardIcon: { width: 40, height: 40, marginBottom: 24, color: C.green },
  cardTitle: { fontFamily: SF, fontSize: 18, fontWeight: 600, color: C.text, marginBottom: 10 },
  cardDesc: { fontSize: 13.5, color: C.muted, lineHeight: 1.65, marginBottom: 28, fontFamily: SFText },
  cardLink: (hovered) => ({ fontSize: 13, color: C.gold, textDecoration: 'none', fontWeight: 500, opacity: hovered ? 1 : 0, transition: 'opacity 0.25s', display: 'inline-flex', alignItems: 'center', gap: 6, fontFamily: SFText }),

  whySection: { background: C.deep, borderTop: `1px solid ${C.border}`, borderBottom: `1px solid ${C.border}`, padding: '120px 48px' },
  whyGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 100, alignItems: 'start' },
  whyLeft: { position: 'sticky', top: 120 },
  whyCta: { fontSize: 14, color: C.gold, textDecoration: 'none', fontWeight: 500, display: 'inline-flex', alignItems: 'center', gap: 6, borderBottom: '1px solid rgba(211,185,136,0.3)', paddingBottom: 2, fontFamily: SFText },
  featureRow: (visible, i) => ({ display: 'grid', gridTemplateColumns: '52px 1fr', gap: 20, padding: '32px 0', borderBottom: '1px solid rgba(92,127,120,0.12)', opacity: visible ? 1 : 0, transform: visible ? 'none' : 'translateX(24px)', transition: `opacity 0.6s ${i * 0.1}s ease, transform 0.6s ${i * 0.1}s ease` }),
  featureNum: { fontFamily: SFMono, fontSize: 12, color: C.bronze, paddingTop: 2 },
  featureTitle: { fontFamily: SF, fontSize: 17, fontWeight: 600, color: C.text, marginBottom: 6 },
  featureDesc: { fontSize: 13.5, color: C.muted, lineHeight: 1.65, fontFamily: SFText },

  ctaSection: { position: 'relative', overflow: 'hidden', textAlign: 'center', padding: '140px 48px', background: C.bg },
  ctaGlow: { position: 'absolute', width: 900, height: 500, left: '50%', top: '50%', transform: 'translate(-50%,-50%)', background: 'radial-gradient(ellipse, rgba(37,64,58,0.5) 0%, transparent 70%)', pointerEvents: 'none' },
  ctaH2: { fontFamily: SF, fontSize: 'clamp(36px,5vw,60px)', fontWeight: 700, lineHeight: 1.06, letterSpacing: '-0.025em', color: C.text, marginBottom: 20 },
  ctaSub: { fontSize: 16, color: C.muted, margin: '0 auto 44px', maxWidth: 440, lineHeight: 1.65, fontFamily: SFText },
  btnGold: { padding: '16px 40px', background: C.gold, color: C.bg, border: 'none', borderRadius: 9999, fontFamily: SFText, fontSize: 15, fontWeight: 500, textDecoration: 'none', display: 'inline-block' },
  ctaSecondary: { fontSize: 13.5, color: C.muted, textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: 4, fontFamily: SFText, marginTop: 16 },

  footer: { background: '#060908', borderTop: `1px solid ${C.border}`, padding: '64px 48px 36px' },
  footerInner: { maxWidth: 1200, margin: '0 auto' },
  footerTop: { display: 'grid', gridTemplateColumns: '1.4fr 1fr 1fr', gap: 64, marginBottom: 56 },
  footerColTitle: { fontFamily: SFMono, fontSize: 10, letterSpacing: '0.18em', textTransform: 'uppercase', color: C.green, marginBottom: 20 },
  footerLink: { fontSize: 13.5, color: C.muted, textDecoration: 'none', display: 'block', marginBottom: 12, fontFamily: SFText },
  footerBottom: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: 28, borderTop: `1px solid ${C.border}` },
  footerCopy: { fontSize: 12, color: 'rgba(122,148,144,0.5)', fontFamily: SFMono },
  footerSocials: { display: 'flex', gap: 20 },
  socialLink: { fontSize: 12, color: C.muted, textDecoration: 'none', fontFamily: SFMono, letterSpacing: '0.06em', textTransform: 'uppercase' },
};
